export const PERSIST_CONFIG = (storage) => ({
  key: 'root',
  storage,
  whitelist: ['cart'], //define what to persist
});

export const USER = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',

  GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
  EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',

  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGNOUT_START: 'SIGNOUT_START',

  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
};

export const CART = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ITEM_ADD: 'ITEM_ADD',
  ITEM_SUBTRACT: 'ITEM_SUBTRACT',
  ITEM_DROP: 'ITEM_DROP',
  CLEAR_CART: 'CLEAR_CART',
};

export const DIRECTORY = {
  SET_DIRECTORY: 'SET_DIRECTORY',
};

export const SHOP = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_',
};
